// .symphony/workspaces/code-quality/lm-4e95ac36/packages/webflow-components/src/components/navigation/Navigation.tsx
import React, { CSSProperties, useMemo, useState } from 'react';
import { tokens } from '../../styles/tokens';
import { Inline, Stack, Text } from '../primitives';

export interface NavigationLink {
  label: string;
  href: string;
}

export interface NavigationProps {
  logo?: string;
  logoSuffix?: string;
  logoHref?: string;
  links?: string;
  currentPath?: string;
  fixed?: boolean;
  ctaLabel?: string;
  ctaHref?: string;
  mobileMenuLabel?: string;
  className?: string;
}

const defaultLinks: NavigationLink[] = [
  { label: 'Home', href: '/' },
  { label: 'Work', href: '/work' },
  { label: 'Papers', href: '/papers' },
  { label: 'Contact', href: '/contact' },
];

function parseLinks(links?: string): NavigationLink[] {
  if (!links) return defaultLinks;

  try {
    const parsed = JSON.parse(links) as NavigationLink[];
    return parsed.length > 0 ? parsed : defaultLinks;
  } catch {
    return defaultLinks;
  }
}

function isActivePath(currentPath: string, href: string) {
  if (href === '/') return currentPath === '/';
  return currentPath.startsWith(href);
}

export const Navigation: React.FC<NavigationProps> = ({
  logo = 'CREATE SOMETHING',
  logoSuffix,
  logoHref = '/',
  links,
  currentPath = '/',
  fixed = false,
  ctaLabel,
  ctaHref,
  mobileMenuLabel = 'Menu',
  className = '',
}) => {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const navLinks = useMemo(() => parseLinks(links), [links]);

  const containerStyles: CSSProperties = {
    position: fixed ? 'fixed' : 'relative',
    top: fixed ? 0 : undefined,
    left: fixed ? 0 : undefined,
    right: fixed ? 0 : undefined,
    zIndex: fixed ? 40 : undefined,
    background: fixed ? tokens.colors.bgPure : 'transparent',
    backdropFilter: fixed ? 'blur(12px)' : undefined,
    WebkitBackdropFilter: fixed ? 'blur(12px)' : undefined,
    borderBottom: `1px solid ${fixed ? tokens.colors.borderDefault : 'transparent'}`,
  };

  const innerStyles: CSSProperties = {
    maxWidth: '1180px',
    margin: '0 auto',
    padding: `${tokens.spacing.sm} ${tokens.spacing.md}`,
  };

  const logoStyles: CSSProperties = {
    color: tokens.colors.fgPrimary,
    textDecoration: 'none',
  };

  const linkBaseStyles: CSSProperties = {
    display: 'inline-flex',
    alignItems: 'center',
    padding: '0.5rem 0.75rem',
    borderRadius: tokens.radii.md,
    color: tokens.colors.fgSecondary,
    textDecoration: 'none',
    fontSize: tokens.typography.fontSize.bodySm,
    fontWeight: tokens.typography.fontWeight.medium,
    transition: `color ${tokens.animation.duration.micro} ${tokens.animation.easing.standard}, background ${tokens.animation.duration.micro} ${tokens.animation.easing.standard}`,
  };

  const ctaStyles: CSSProperties = {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: '40px',
    padding: '0.625rem 1rem',
    borderRadius: tokens.radii.lg,
    background: tokens.colors.fgPrimary,
    color: tokens.colors.bgPure,
    textDecoration: 'none',
    fontSize: tokens.typography.fontSize.bodySm,
    fontWeight: tokens.typography.fontWeight.semibold,
    border: '1px solid transparent',
  };

  const mobileButtonStyles: CSSProperties = {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: '44px',
    minHeight: '44px',
    padding: '0.5rem',
    border: `1px solid ${tokens.colors.borderDefault}`,
    borderRadius: tokens.radii.md,
    background: tokens.colors.bgSurface,
    color: tokens.colors.fgPrimary,
  };

  const mobilePanelStyles: CSSProperties = {
    display: mobileMenuOpen ? 'flex' : 'none',
    flexDirection: 'column',
    gap: tokens.spacing.sm,
    marginTop: tokens.spacing.sm,
    padding: tokens.spacing.sm,
    borderRadius: tokens.radii.lg,
    background: tokens.colors.bgSurface,
    border: `1px solid ${tokens.colors.borderDefault}`,
  };

  const navigationCss = `
    .canon-navigation-link:hover {
      color: ${tokens.colors.fgPrimary};
      background: ${tokens.colors.hover};
    }
    .canon-navigation-link[data-active="true"] {
      color: ${tokens.colors.fgPrimary};
      background: ${tokens.colors.active};
    }
    .canon-navigation-link:focus-visible,
    .canon-navigation-cta:focus-visible,
    .canon-navigation-mobile-toggle:focus-visible,
    .canon-navigation-mobile-link:focus-visible {
      outline: 2px solid ${tokens.colors.focus};
      outline-offset: 2px;
    }
    .canon-navigation-cta:hover {
      opacity: 0.92;
    }
    @media (max-width: ${tokens.breakpoints.lg}) {
      .canon-navigation-desktop {
        display: none !important;
      }
    }
    @media (min-width: ${tokens.breakpoints.lg}) {
      .canon-navigation-mobile-toggle,
      .canon-navigation-mobile-panel {
        display: none !important;
      }
    }
  `;

  return (
    <nav className={className} style={containerStyles} aria-label="Primary">
      <style>{navigationCss}</style>
      <div style={innerStyles}>
        <Inline justify="space-between" align="center" wrap="nowrap">
          <a href={logoHref} style={logoStyles}>
            <Inline gap="xs" align="baseline" wrap="nowrap">
              <Text as="span" size="h5" weight="bold" tone="primary">
                {logo}
              </Text>
              {logoSuffix ? (
                <Text as="span" size="sm" tone="tertiary">
                  {logoSuffix}
                </Text>
              ) : null}
            </Inline>
          </a>

          <Inline className="canon-navigation-desktop" gap="xs" align="center" wrap="nowrap">
            {navLinks.map((link) => {
              const active = isActivePath(currentPath, link.href);
              return (
                <a
                  key={link.href}
                  href={link.href}
                  className="canon-navigation-link"
                  data-active={active}
                  style={linkBaseStyles}
                  aria-current={active ? 'page' : undefined}
                >
                  {link.label}
                </a>
              );
            })}

            {ctaLabel && ctaHref ? (
              <a href={ctaHref} className="canon-navigation-cta" style={ctaStyles}>
                {ctaLabel}
              </a>
            ) : null}
          </Inline>

          <button
            type="button"
            className="canon-navigation-mobile-toggle"
            style={mobileButtonStyles}
            onClick={() => setMobileMenuOpen((open) => !open)}
            aria-expanded={mobileMenuOpen}
            aria-label={mobileMenuOpen ? 'Close menu' : 'Open menu'}
          >
            <span style={{ position: 'absolute', width: 1, height: 1, overflow: 'hidden', clip: 'rect(0, 0, 0, 0)' }}>
              {mobileMenuLabel}
            </span>
            <svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true">
              {mobileMenuOpen ? (
                <path d="M6 18L18 6M6 6l12 12" />
              ) : (
                <path d="M4 6h16M4 12h16M4 18h16" />
              )}
            </svg>
          </button>
        </Inline>

        <Stack className="canon-navigation-mobile-panel" style={mobilePanelStyles}>
          {navLinks.map((link) => {
            const active = isActivePath(currentPath, link.href);
            return (
              <a
                key={link.href}
                href={link.href}
                className="canon-navigation-mobile-link canon-navigation-link"
                data-active={active}
                style={{ ...linkBaseStyles, width: '100%' }}
                aria-current={active ? 'page' : undefined}
                onClick={() => setMobileMenuOpen(false)}
              >
                {link.label}
              </a>
            );
          })}

          {ctaLabel && ctaHref ? (
            <a href={ctaHref} className="canon-navigation-cta" style={ctaStyles} onClick={() => setMobileMenuOpen(false)}>
              {ctaLabel}
            </a>
          ) : null}
        </Stack>
      </div>
    </nav>
  );
};

export default Navigation;

// packages/canon/src/lib/components/Navigation.svelte
<script lang="ts">
	import { UserMenu } from '../auth/components/index.js';
	import type { User } from '../auth/types.js';

	interface NavLink {
		label: string;
		href: string;
	}

	interface Props {
		logo: string;
		logoSuffix?: string;
		logoHref?: string;
		links: NavLink[];
		currentPath?: string;
		fixed?: boolean;
		ctaLabel?: string;
		ctaHref?: string;
		/** Current authenticated user (shows UserMenu when present) */
		user?: User | null;
		/** Called when user clicks logout in UserMenu */
		onLogout?: () => void;
		/** Login page URL (shown when no user) */
		loginHref?: string;
		/** Show login link when not authenticated */
		showLogin?: boolean;
		/** Account settings URL for UserMenu */
		accountHref?: string;
	}

	let {
		logo,
		logoSuffix,
		logoHref = '/',
		links,
		currentPath = $bindable('/'),
		fixed = false,
		ctaLabel,
		ctaHref,
		user = null,
		onLogout,
		loginHref = '/login',
		showLogin = false,
		accountHref = '/account'
	}: Props = $props();

	let mobileMenuOpen = $state(false);

	function isActive(link: NavLink): boolean {
		if (link.href === '/') {
			return currentPath === '/';
		}
		return currentPath.startsWith(link.href);
	}

	function toggleMobileMenu() {
		mobileMenuOpen = !mobileMenuOpen;
	}

	function closeMobileMenu() {
		mobileMenuOpen = false;
	}
</script>

<nav class="nav-container" class:nav-fixed={fixed} aria-label="Primary">
	<div class="nav-inner shell-inner">
		<div class="flex items-center justify-between">
			<!-- Logo / Home -->
			<a href={logoHref} class="nav-logo">
				{logo}
				{#if logoSuffix}
					<span class="nav-logo-suffix">{logoSuffix}</span>
				{/if}
			</a>

			<!-- Desktop Navigation Links -->
			<div class="nav-desktop hidden lg:flex items-center gap-2 ml-8">
				{#each links as link}
					<a href={link.href} class="nav-link" class:active={isActive(link)}>
						{link.label}
					</a>
				{/each}
				{#if ctaLabel && ctaHref}
					<a href={ctaHref} class="nav-cta">
						{ctaLabel}
					</a>
				{/if}
				{#if user}
					<UserMenu {user} onLogout={onLogout ?? (() => {})} settingsHref={accountHref} />
				{:else if showLogin}
					<a href={loginHref} class="nav-link">
						Sign in
					</a>
				{/if}
			</div>

			<!-- Mobile Menu Button (44px minimum touch target) -->
			<button
				onclick={toggleMobileMenu}
				class="nav-menu-button lg:hidden w-11 h-11 flex items-center justify-center"
				aria-label={mobileMenuOpen ? 'Close menu' : 'Open menu'}
				aria-expanded={mobileMenuOpen}
			>
				{#if mobileMenuOpen}
					<!-- Close Icon (X) -->
					<svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
						<path
							stroke-linecap="round"
							stroke-linejoin="round"
							stroke-width="2"
							d="M6 18L18 6M6 6l12 12"
						/>
					</svg>
				{:else}
					<!-- Hamburger Icon -->
					<svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
						<path
							stroke-linecap="round"
							stroke-linejoin="round"
							stroke-width="2"
							d="M4 6h16M4 12h16M4 18h16"
						/>
					</svg>
				{/if}
			</button>
		</div>

		<!-- Mobile Menu -->
		{#if mobileMenuOpen}
			<div class="nav-mobile-menu animate-slide-down lg:hidden pt-4 pb-2 flex flex-col gap-4 mt-4">
				{#each links as link}
					<a href={link.href} onclick={closeMobileMenu} class="nav-link py-2" class:active={isActive(link)}>
						{link.label}
					</a>
				{/each}
				{#if ctaLabel && ctaHref}
					<a href={ctaHref} onclick={closeMobileMenu} class="nav-cta text-center">
						{ctaLabel}
					</a>
				{/if}
				{#if user}
					<div class="nav-mobile-user">
						<span class="nav-mobile-user-email">{user.email}</span>
						<a href={accountHref} onclick={closeMobileMenu} class="nav-link py-2">
							Account
						</a>
						<button type="button" class="nav-mobile-logout" onclick={() => { closeMobileMenu(); onLogout?.(); }}>
							Sign out
						</button>
					</div>
				{:else if showLogin}
					<a href={loginHref} onclick={closeMobileMenu} class="nav-link py-2">
						Sign in
					</a>
				{/if}
			</div>
		{/if}
	</div>
</nav>

<style>
	/* Navigation Container */
	.nav-container {
		border-bottom: 1px solid var(--color-shell-border-default);
		background: var(--color-shell-surface);
	}

	.nav-inner {
		padding: 0.875rem var(--container-padding, 1.5rem);
		display: flex;
		flex-direction: column;
	}

	.nav-fixed {
		position: fixed;
		top: 0;
		left: 0;
		right: 0;
		width: 100%;
		z-index: var(--z-fixed);
		background-color: color-mix(in srgb, var(--color-shell-surface) 86%, transparent);
		backdrop-filter: blur(12px);
		-webkit-backdrop-filter: blur(12px);
		border-bottom: 1px solid var(--color-shell-border-default);
		box-shadow: var(--color-shell-shadow);
	}

	/* Logo */
	.nav-logo {
		font-size: 1.25rem;
		font-weight: var(--font-bold);
		letter-spacing: -0.02em;
		color: var(--color-fg-primary);
		text-decoration: none;
	}

	.nav-logo-suffix {
		font-weight: normal;
		color: var(--color-fg-tertiary);
	}

	/* Navigation Links */
	.nav-link {
		font-size: var(--text-body-sm);
		font-weight: var(--font-medium);
		color: var(--color-fg-secondary);
		text-decoration: none;
		border-radius: var(--radius-md);
		padding: 0.4rem 0.7rem;
		transition:
			color var(--duration-micro) var(--ease-standard),
			background-color var(--duration-micro) var(--ease-standard),
			border-color var(--duration-micro) var(--ease-standard);
	}

	.nav-link:hover {
		color: var(--color-fg-primary);
		background: var(--color-shell-surface-hover);
	}

	.nav-link.active {
		color: var(--color-fg-primary);
		background: var(--color-shell-surface-tertiary);
	}

	.nav-link:focus-visible {
		outline: 2px solid var(--color-focus);
		outline-offset: 2px;
	}

	/* CTA Button */
	.nav-cta {
		padding: 0.5rem 1rem;
		background: var(--color-fg-primary);
		color: var(--color-bg-pure);
		font-size: var(--text-body-sm);
		font-weight: var(--font-semibold);
		border-radius: var(--radius-lg);
		border: 1px solid transparent;
		text-decoration: none;
		transition:
			opacity var(--duration-micro) var(--ease-standard),
			transform var(--duration-micro) var(--ease-standard);
	}

	.nav-cta:hover {
		opacity: 0.9;
		transform: translateY(-1px);
	}

	.nav-cta:focus-visible {
		outline: 2px solid var(--color-focus);
		outline-offset: 2px;
	}

	.nav-desktop {
		border: 1px solid var(--color-shell-border-subtle);
		background: color-mix(in srgb, var(--color-shell-surface-secondary) 88%, transparent);
		border-radius: var(--radius-full);
		padding: 0.25rem;
	}

	/* Mobile Menu Button */
	.nav-menu-button {
		color: var(--color-fg-primary);
		background: var(--color-shell-surface-tertiary);
		border: 1px solid var(--color-shell-border-default);
		border-radius: var(--radius-md);
		transition:
			color var(--duration-micro) var(--ease-standard),
			background var(--duration-micro) var(--ease-standard),
			border-color var(--duration-micro) var(--ease-standard);
	}

	.nav-menu-button:hover {
		background: var(--color-shell-surface-hover);
		border-color: var(--color-shell-border-strong);
	}

	.nav-menu-button:focus-visible {
		outline: 2px solid var(--color-focus);
		outline-offset: 2px;
	}

	/* Mobile Menu */
	.nav-mobile-menu {
		border: 1px solid var(--color-shell-border-default);
		background: var(--color-shell-surface-secondary);
		border-radius: var(--radius-lg);
		padding-left: var(--space-sm);
		padding-right: var(--space-sm);
		box-shadow: var(--color-shell-shadow);
	}

	/* Slide down animation for mobile menu */
	.animate-slide-down {
		animation: slide-down 0.2s cubic-bezier(0.4, 0, 0.2, 1) forwards;
	}

	@keyframes slide-down {
		from {
			opacity: 0;
			transform: translateY(-8px);
		}
		to {
			opacity: 1;
			transform: translateY(0);
		}
	}

	@media (prefers-reduced-motion: reduce) {
		.animate-slide-down {
			animation: none;
		}
	}

	/* Mobile User Section */
	.nav-mobile-user {
		border-top: 1px solid var(--color-border-default);
		padding-top: var(--space-sm);
		margin-top: var(--space-sm);
		display: flex;
		flex-direction: column;
		gap: var(--space-xs);
	}

	.nav-mobile-user-email {
		font-size: var(--text-body-sm);
		color: var(--color-fg-muted);
		padding: var(--space-xs) 0;
	}

	.nav-mobile-logout {
		background: none;
		border: none;
		color: var(--color-error);
		font-size: var(--text-body-sm);
		font-weight: var(--font-medium);
		padding: var(--space-sm) 0;
		text-align: left;
		cursor: pointer;
		transition: opacity var(--duration-micro) var(--ease-standard);
	}

	.nav-mobile-logout:hover {
		opacity: 0.8;
	}
</style>
