// packages/webflow-components/src/components/navigation/Tabs.tsx
import React, { CSSProperties, KeyboardEvent, useId, useMemo, useState } from 'react';
import { tokens } from '../../styles/tokens';

export interface TabItem {
  id: string;
  label: string;
  content?: string;
  disabled?: boolean;
}

export type TabsVariant = 'default' | 'pills' | 'underline';
export type TabsSize = 'sm' | 'md' | 'lg';

export interface TabsProps {
  tabs?: string;
  activeTab?: string;
  variant?: TabsVariant;
  size?: TabsSize;
  className?: string;
}

const defaultTabs: TabItem[] = [
  { id: 'overview', label: 'Overview', content: 'A reusable Canon tabs primitive for Webflow.' },
  { id: 'details', label: 'Details', content: 'Switch between panels with keyboard and pointer interaction.' },
  { id: 'notes', label: 'Notes', content: 'Use JSON input to define labels, ids, and panel content.' },
];

function parseTabs(tabs?: string): TabItem[] {
  if (!tabs) return defaultTabs;

  try {
    const parsed = JSON.parse(tabs) as TabItem[];
    return parsed.length > 0 ? parsed : defaultTabs;
  } catch {
    return defaultTabs;
  }
}

const sizeStyles: Record<TabsSize, { padding: string; fontSize: string }> = {
  sm: { padding: '0.5rem 0.75rem', fontSize: tokens.typography.fontSize.bodySm },
  md: { padding: '0.75rem 1rem', fontSize: tokens.typography.fontSize.body },
  lg: { padding: '1rem 1.25rem', fontSize: tokens.typography.fontSize.bodyLg },
};

export const Tabs: React.FC<TabsProps> = ({
  tabs,
  activeTab,
  variant = 'default',
  size = 'md',
  className = '',
}) => {
  const instanceId = useId();
  const parsedTabs = useMemo(() => parseTabs(tabs), [tabs]);
  const enabledTabs = parsedTabs.filter((tab) => !tab.disabled);
  const [internalActiveTab, setInternalActiveTab] = useState(
    activeTab || enabledTabs[0]?.id || parsedTabs[0]?.id || ''
  );

  const currentActiveTab = activeTab || internalActiveTab;
  const activePanel = parsedTabs.find((tab) => tab.id === currentActiveTab) || parsedTabs[0];
  const tabSize = sizeStyles[size];

  const listStyles: CSSProperties = {
    display: 'flex',
    gap: variant === 'underline' ? tokens.spacing.md : '4px',
    borderBottom: variant === 'default' ? `1px solid ${tokens.colors.borderDefault}` : 'none',
    background: variant === 'pills' ? tokens.colors.bgSubtle : 'transparent',
    padding: variant === 'pills' ? '4px' : 0,
    borderRadius: variant === 'pills' ? tokens.radii.md : undefined,
    width: variant === 'pills' ? 'fit-content' : undefined,
  };

  const panelStyles: CSSProperties = {
    padding: `${tokens.spacing.md} 0`,
    color: tokens.colors.fgSecondary,
    fontSize: tokens.typography.fontSize.body,
    lineHeight: tokens.typography.lineHeight.relaxed,
  };

  const getTabStyles = (isActive: boolean): CSSProperties => ({
    position: 'relative',
    background: variant === 'pills' && isActive ? tokens.colors.fgPrimary : 'transparent',
    color:
      variant === 'pills' && isActive ? tokens.colors.bgPure : isActive ? tokens.colors.fgPrimary : tokens.colors.fgMuted,
    border: 'none',
    borderRadius: variant === 'pills' ? tokens.radii.sm : undefined,
    padding: variant === 'underline' ? `${tabSize.padding} 0` : tabSize.padding,
    fontSize: tabSize.fontSize,
    fontWeight: tokens.typography.fontWeight.medium,
    cursor: 'pointer',
    transition: `all ${tokens.animation.duration.micro} ${tokens.animation.easing.standard}`,
    whiteSpace: 'nowrap',
    boxShadow: variant === 'pills' && isActive ? tokens.shadows.sm : undefined,
  });

  const tabsCss = `
    .canon-tabs-button:hover:not(:disabled) {
      color: ${tokens.colors.fgPrimary};
    }
    .canon-tabs-button:focus-visible {
      outline: 2px solid ${tokens.colors.focus};
      outline-offset: -2px;
      border-radius: ${tokens.radii.sm};
    }
    .canon-tabs-button:disabled {
      opacity: 0.5;
      cursor: not-allowed;
    }
    .canon-tabs-button[data-variant="default"][data-active="true"]::after,
    .canon-tabs-button[data-variant="underline"][data-active="true"]::after {
      content: '';
      position: absolute;
      left: 0;
      right: 0;
      bottom: -1px;
      height: 2px;
      background: ${tokens.colors.fgPrimary};
    }
  `;

  const selectTab = (tabId: string) => {
    const candidate = parsedTabs.find((tab) => tab.id === tabId);
    if (!candidate || candidate.disabled) return;
    setInternalActiveTab(tabId);
  };

  const handleKeyDown = (event: KeyboardEvent<HTMLDivElement>) => {
    const currentIndex = enabledTabs.findIndex((tab) => tab.id === currentActiveTab);
    if (currentIndex < 0) return;

    let nextIndex = currentIndex;

    switch (event.key) {
      case 'ArrowLeft':
        event.preventDefault();
        nextIndex = currentIndex > 0 ? currentIndex - 1 : enabledTabs.length - 1;
        break;
      case 'ArrowRight':
        event.preventDefault();
        nextIndex = currentIndex < enabledTabs.length - 1 ? currentIndex + 1 : 0;
        break;
      case 'Home':
        event.preventDefault();
        nextIndex = 0;
        break;
      case 'End':
        event.preventDefault();
        nextIndex = enabledTabs.length - 1;
        break;
      default:
        return;
    }

    const nextTab = enabledTabs[nextIndex];
    if (!nextTab) return;
    selectTab(nextTab.id);
    requestAnimationFrame(() => {
      const nextButton = document.getElementById(`${instanceId}-tab-${nextTab.id}`);
      nextButton?.focus();
    });
  };

  return (
    <div className={className}>
      <style>{tabsCss}</style>

      <div role="tablist" aria-orientation="horizontal" style={listStyles} onKeyDown={handleKeyDown}>
        {parsedTabs.map((tab) => {
          const isActive = currentActiveTab === tab.id;
          return (
            <button
              key={tab.id}
              id={`${instanceId}-tab-${tab.id}`}
              type="button"
              role="tab"
              aria-selected={isActive}
              aria-controls={`${instanceId}-panel-${tab.id}`}
              tabIndex={isActive ? 0 : -1}
              disabled={tab.disabled}
              className="canon-tabs-button"
              data-active={isActive}
              data-variant={variant}
              style={getTabStyles(isActive)}
              onClick={() => selectTab(tab.id)}
            >
              {tab.label}
            </button>
          );
        })}
      </div>

      {activePanel ? (
        <div
          id={`${instanceId}-panel-${activePanel.id}`}
          role="tabpanel"
          aria-labelledby={`${instanceId}-tab-${activePanel.id}`}
          tabIndex={0}
          style={panelStyles}
        >
          {activePanel.content || ''}
        </div>
      ) : null}
    </div>
  );
};

export default Tabs;

// packages/canon/src/lib/components/navigation/Tabs.svelte
<script lang="ts">
	/**
	 * Tabs Component
	 *
	 * Tab panel interface with keyboard navigation following WAI-ARIA tabs pattern.
	 * Supports arrow key navigation between tabs.
	 *
	 * Canon: The tabs organize; content surfaces.
	 */

	import type { Snippet } from 'svelte';

	interface Tab {
		/** Unique tab identifier */
		id: string;
		/** Tab label */
		label: string;
		/** Whether tab is disabled */
		disabled?: boolean;
	}

	interface Props {
		/** Tab definitions */
		tabs: Tab[];
		/** Currently active tab ID (bindable) */
		activeTab?: string;
		/** Tab panel content - receives activeTab as parameter */
		children: Snippet<[string]>;
		/** Called when active tab changes */
		onchange?: (tabId: string) => void;
		/** Visual variant */
		variant?: 'default' | 'pills' | 'underline';
		/** Size variant */
		size?: 'sm' | 'md' | 'lg';
	}

	let {
		tabs,
		activeTab = $bindable(tabs[0]?.id ?? ''),
		children,
		onchange,
		variant = 'default',
		size = 'md'
	}: Props = $props();

	let tablistRef: HTMLDivElement;

	function selectTab(tabId: string) {
		const tab = tabs.find((t) => t.id === tabId);
		if (tab && !tab.disabled) {
			activeTab = tabId;
			onchange?.(tabId);
		}
	}

	function handleKeyDown(event: KeyboardEvent) {
		const enabledTabs = tabs.filter((t) => !t.disabled);
		const currentIndex = enabledTabs.findIndex((t) => t.id === activeTab);

		let newIndex = currentIndex;

		switch (event.key) {
			case 'ArrowLeft':
				event.preventDefault();
				newIndex = currentIndex > 0 ? currentIndex - 1 : enabledTabs.length - 1;
				break;
			case 'ArrowRight':
				event.preventDefault();
				newIndex = currentIndex < enabledTabs.length - 1 ? currentIndex + 1 : 0;
				break;
			case 'Home':
				event.preventDefault();
				newIndex = 0;
				break;
			case 'End':
				event.preventDefault();
				newIndex = enabledTabs.length - 1;
				break;
			default:
				return;
		}

		const newTab = enabledTabs[newIndex];
		if (newTab) {
			selectTab(newTab.id);
			// Focus the new tab button
			const tabButton = tablistRef?.querySelector(`[data-tab-id="${newTab.id}"]`) as HTMLElement;
			tabButton?.focus();
		}
	}
</script>

<div class="tabs tabs-{variant} tabs-{size}">
		<div
			class="tabs-list"
			role="tablist"
			tabindex={0}
			bind:this={tablistRef}
			onkeydown={handleKeyDown}
		>
		{#each tabs as tab}
			<button
				type="button"
				role="tab"
				id="tab-{tab.id}"
				data-tab-id={tab.id}
				class="tabs-tab"
				class:active={activeTab === tab.id}
				aria-selected={activeTab === tab.id}
				aria-controls="panel-{tab.id}"
				tabindex={activeTab === tab.id ? 0 : -1}
				disabled={tab.disabled}
				onclick={() => selectTab(tab.id)}
			>
				{tab.label}
			</button>
		{/each}
	</div>

	{#each tabs as tab}
		<div
			id="panel-{tab.id}"
			role="tabpanel"
			aria-labelledby="tab-{tab.id}"
			class="tabs-panel"
			class:active={activeTab === tab.id}
			hidden={activeTab !== tab.id}
			tabindex={0}
		>
			{#if activeTab === tab.id}
				{@render children(tab.id)}
			{/if}
		</div>
	{/each}
</div>

<style>
	.tabs {
		display: flex;
		flex-direction: column;
	}

	/* Tab list */
	.tabs-list {
		display: flex;
		gap: 2px;
		border-bottom: 1px solid var(--color-border-default);
	}

	/* Tab button base */
	.tabs-tab {
		position: relative;
		padding: var(--space-sm) var(--space-md);
		background: none;
		border: none;
		color: var(--color-fg-muted);
		font-size: var(--text-body);
		font-weight: var(--font-medium);
		cursor: pointer;
		transition: all var(--duration-micro) var(--ease-standard);
		white-space: nowrap;
	}

	.tabs-tab:hover:not(:disabled) {
		color: var(--color-fg-primary);
	}

	.tabs-tab:focus-visible {
		outline: 2px solid var(--color-focus);
		outline-offset: -2px;
		border-radius: var(--radius-sm);
	}

	.tabs-tab:disabled {
		opacity: 0.5;
		cursor: not-allowed;
	}

	.tabs-tab.active {
		color: var(--color-fg-primary);
	}

	/* Default variant - underline indicator */
	.tabs-default .tabs-tab::after {
		content: '';
		position: absolute;
		bottom: -1px;
		left: 0;
		right: 0;
		height: 2px;
		background: transparent;
		transition: background var(--duration-micro) var(--ease-standard);
	}

	.tabs-default .tabs-tab.active::after {
		background: var(--color-fg-primary);
	}

	/* Pills variant */
	.tabs-pills .tabs-list {
		border-bottom: none;
		gap: var(--space-xs);
		background: var(--color-bg-subtle);
		padding: 4px;
		border-radius: var(--radius-md);
		width: fit-content;
	}

	.tabs-pills .tabs-tab {
		border-radius: var(--radius-sm);
		padding: var(--space-xs) var(--space-sm);
	}

	.tabs-pills .tabs-tab.active {
		background: var(--color-bg-elevated);
		box-shadow: var(--shadow-sm);
	}

	/* Underline variant - minimal */
	.tabs-underline .tabs-list {
		gap: var(--space-md);
	}

	.tabs-underline .tabs-tab {
		padding: var(--space-sm) 0;
	}

	.tabs-underline .tabs-tab::after {
		content: '';
		position: absolute;
		bottom: -1px;
		left: 0;
		right: 0;
		height: 2px;
		background: transparent;
		transition: background var(--duration-micro) var(--ease-standard);
	}

	.tabs-underline .tabs-tab.active::after {
		background: var(--color-fg-primary);
	}

	/* Size variants */
	.tabs-sm .tabs-tab {
		padding: var(--space-xs) var(--space-sm);
		font-size: var(--text-body-sm);
	}

	.tabs-lg .tabs-tab {
		padding: var(--space-md) var(--space-lg);
		font-size: var(--text-body-lg);
	}

	/* Panel */
	.tabs-panel {
		padding: var(--space-md) 0;
	}

	.tabs-panel:focus-visible {
		outline: 2px solid var(--color-focus);
		outline-offset: 2px;
		border-radius: var(--radius-sm);
	}

	.tabs-panel[hidden] {
		display: none;
	}
</style>
