// packages/canon/src/lib/components/form/TextField.svelte
<script lang="ts">
	/**
	 * TextField Component
	 *
	 * A fully accessible text input with label, description, and error handling.
	 * Follows Canon design system tokens for consistent styling.
	 *
	 * Canon: The form field disappears; only the input remains.
	 */

	import type { HTMLInputAttributes } from 'svelte/elements';

	interface Props {
		/** Input value (bindable) */
		value?: string;
		/** Field label */
		label?: string;
		/** Input type */
		type?: 'text' | 'email' | 'password' | 'tel' | 'url' | 'search' | 'number';
		/** Placeholder text */
		placeholder?: string;
		/** Helper description below input */
		description?: string;
		/** Error message (shows error state when set) */
		error?: string | null;
		/** Whether field is required */
		required?: boolean;
		/** Whether field is disabled */
		disabled?: boolean;
		/** Whether field is readonly */
		readonly?: boolean;
		/** Input name attribute */
		name?: string;
		/** Input id (auto-generated if not provided) */
		id?: string;
		/** Autocomplete attribute */
		autocomplete?: HTMLInputAttributes['autocomplete'];
		/** Input pattern for validation */
		pattern?: string;
		/** Minimum length */
		minlength?: number;
		/** Maximum length */
		maxlength?: number;
		/** Size variant */
		size?: 'sm' | 'md' | 'lg';
		/** Called on input change */
		oninput?: (event: Event & { currentTarget: HTMLInputElement }) => void;
		/** Called on blur */
		onblur?: (event: FocusEvent & { currentTarget: HTMLInputElement }) => void;
		/** Called on focus */
		onfocus?: (event: FocusEvent & { currentTarget: HTMLInputElement }) => void;
	}

	let {
		value = $bindable(''),
		label,
		type = 'text',
		placeholder,
		description,
		error = null,
		required = false,
		disabled = false,
		readonly = false,
		name,
		id,
		autocomplete,
		pattern,
		minlength,
		maxlength,
		size = 'md',
		oninput,
		onblur,
		onfocus
	}: Props = $props();

	// Generate unique ID if not provided
	const fieldId = id || `textfield-${crypto.randomUUID().slice(0, 8)}`;
	const descriptionId = `${fieldId}-description`;
	const errorId = `${fieldId}-error`;

	// Determine aria-describedby based on what's shown
	const ariaDescribedBy = $derived(
		[error ? errorId : null, description ? descriptionId : null].filter(Boolean).join(' ') || undefined
	);
</script>

<div class="textfield" class:textfield-sm={size === 'sm'} class:textfield-lg={size === 'lg'} class:has-error={error}>
	{#if label}
		<label for={fieldId} class="textfield-label">
			{label}
			{#if required}
				<span class="required-indicator" aria-hidden="true">*</span>
			{/if}
		</label>
	{/if}

	<input
		{type}
		id={fieldId}
		{name}
		bind:value
		{placeholder}
		{disabled}
		{readonly}
		{required}
		{autocomplete}
		{pattern}
		{minlength}
		{maxlength}
		class="textfield-input"
		aria-invalid={error ? 'true' : undefined}
		aria-describedby={ariaDescribedBy}
		aria-required={required ? 'true' : undefined}
		{oninput}
		{onblur}
		{onfocus}
	/>

	{#if error}
		<p id={errorId} class="textfield-error" role="alert">
			{error}
		</p>
	{:else if description}
		<p id={descriptionId} class="textfield-description">
			{description}
		</p>
	{/if}
</div>

<style>
	.textfield {
		display: flex;
		flex-direction: column;
		gap: var(--space-xs);
	}

	/* Label */
	.textfield-label {
		font-size: var(--text-body-sm);
		font-weight: var(--font-medium);
		color: var(--color-fg-secondary);
	}

	.required-indicator {
		color: var(--color-error);
		margin-left: 2px;
	}

	/* Input */
	.textfield-input {
		width: 100%;
		padding: var(--space-sm) var(--space-md);
		background: var(--color-bg-elevated);
		border: 1px solid var(--color-border-default);
		border-radius: var(--radius-md);
		color: var(--color-fg-primary);
		font-size: var(--text-body);
		font-family: inherit;
		transition: border-color var(--duration-micro) var(--ease-standard),
			box-shadow var(--duration-micro) var(--ease-standard);
		min-height: 44px; /* WCAG touch target */
	}

	.textfield-input::placeholder {
		color: var(--color-fg-muted);
	}

	.textfield-input:hover:not(:disabled):not(:focus) {
		border-color: var(--color-border-emphasis);
	}

	.textfield-input:focus {
		outline: none;
		border-color: var(--color-border-emphasis);
		box-shadow: 0 0 0 3px var(--color-focus);
	}

	.textfield-input:disabled {
		opacity: 0.5;
		cursor: not-allowed;
		background: var(--color-bg-subtle);
	}

	.textfield-input:read-only {
		background: var(--color-bg-subtle);
		cursor: default;
	}

	/* Error state */
	.has-error .textfield-input {
		border-color: var(--color-error);
	}

	.has-error .textfield-input:focus {
		box-shadow: 0 0 0 3px var(--color-error-muted);
	}

	/* Size variants */
	.textfield-sm .textfield-input {
		padding: var(--space-xs) var(--space-sm);
		font-size: var(--text-body-sm);
		min-height: 36px;
	}

	.textfield-sm .textfield-label {
		font-size: var(--text-caption);
	}

	.textfield-lg .textfield-input {
		padding: var(--space-md) var(--space-lg);
		font-size: var(--text-body-lg);
		min-height: 52px;
	}

	.textfield-lg .textfield-label {
		font-size: var(--text-body);
	}

	/* Description */
	.textfield-description {
		font-size: var(--text-caption);
		color: var(--color-fg-muted);
		margin: 0;
	}

	/* Error message */
	.textfield-error {
		font-size: var(--text-caption);
		color: var(--color-error);
		margin: 0;
	}
</style>

// .symphony/workspaces/code-quality/lm-4e95ac36/packages/webflow-components/src/components/form/TextField.tsx
import React, { CSSProperties, useId } from 'react';
import { tokens } from '../../styles/tokens';

export type TextFieldType =
  | 'text'
  | 'email'
  | 'password'
  | 'tel'
  | 'url'
  | 'search'
  | 'number';

export type TextFieldSize = 'sm' | 'md' | 'lg';

export interface TextFieldProps {
  label?: string;
  type?: TextFieldType;
  placeholder?: string;
  description?: string;
  error?: string;
  required?: boolean;
  disabled?: boolean;
  readOnly?: boolean;
  name?: string;
  fieldName?: string;
  id?: string;
  autoComplete?: string;
  pattern?: string;
  minLength?: number;
  maxLength?: number;
  size?: TextFieldSize;
  value?: string;
  className?: string;
}

const sizeStyles: Record<TextFieldSize, { minHeight: string; padding: string; fontSize: string; labelSize: string }> = {
  sm: {
    minHeight: '36px',
    padding: '0.5rem 1rem',
    fontSize: tokens.typography.fontSize.bodySm,
    labelSize: tokens.typography.fontSize.caption,
  },
  md: {
    minHeight: '44px',
    padding: '0.75rem 1rem',
    fontSize: tokens.typography.fontSize.body,
    labelSize: tokens.typography.fontSize.bodySm,
  },
  lg: {
    minHeight: '52px',
    padding: '1rem 1.25rem',
    fontSize: tokens.typography.fontSize.bodyLg,
    labelSize: tokens.typography.fontSize.body,
  },
};

export const TextField: React.FC<TextFieldProps> = ({
  label,
  type = 'text',
  placeholder,
  description,
  error,
  required = false,
  disabled = false,
  readOnly = false,
  name,
  fieldName,
  id,
  autoComplete,
  pattern,
  minLength,
  maxLength,
  size = 'md',
  value,
  className = '',
}) => {
  const generatedId = useId();
  const fieldId = id || generatedId;
  const descriptionId = description ? `${fieldId}-description` : undefined;
  const errorId = error ? `${fieldId}-error` : undefined;
  const describedBy = [errorId, descriptionId].filter(Boolean).join(' ') || undefined;
  const htmlName = name || fieldName;
  const fieldSize = sizeStyles[size];

  const containerStyles: CSSProperties = {
    display: 'flex',
    flexDirection: 'column',
    gap: tokens.spacing.xs,
    width: '100%',
  };

  const labelStyles: CSSProperties = {
    color: tokens.colors.fgSecondary,
    fontSize: fieldSize.labelSize,
    fontWeight: tokens.typography.fontWeight.medium,
    fontFamily: tokens.typography.fontFamily.sans,
  };

  const inputStyles: CSSProperties = {
    width: '100%',
    minHeight: fieldSize.minHeight,
    padding: fieldSize.padding,
    borderRadius: tokens.radii.md,
    border: `1px solid ${error ? tokens.colors.error : tokens.colors.borderDefault}`,
    background: disabled || readOnly ? tokens.colors.bgSubtle : tokens.colors.bgSurface,
    color: tokens.colors.fgPrimary,
    fontSize: fieldSize.fontSize,
    fontFamily: tokens.typography.fontFamily.sans,
    transition: `border-color ${tokens.animation.duration.micro} ${tokens.animation.easing.standard}, box-shadow ${tokens.animation.duration.micro} ${tokens.animation.easing.standard}`,
    outline: 'none',
    opacity: disabled ? 0.5 : 1,
  };

  const helperStyles: CSSProperties = {
    margin: 0,
    color: error ? tokens.colors.error : tokens.colors.fgMuted,
    fontSize: tokens.typography.fontSize.caption,
    fontFamily: tokens.typography.fontFamily.sans,
  };

  const fieldCss = `
    .canon-textfield-input::placeholder {
      color: ${tokens.colors.fgMuted};
    }
    .canon-textfield-input:hover:not(:disabled):not(:read-only):not(:focus) {
      border-color: ${tokens.colors.borderEmphasis};
    }
    .canon-textfield-input:focus {
      border-color: ${error ? tokens.colors.error : tokens.colors.borderEmphasis};
      box-shadow: 0 0 0 3px ${error ? tokens.colors.errorMuted : tokens.colors.focus};
    }
  `;

  return (
    <div className={className} style={containerStyles}>
      <style>{fieldCss}</style>

      {label ? (
        <label htmlFor={fieldId} style={labelStyles}>
          {label}
          {required ? <span style={{ color: tokens.colors.error }}> *</span> : null}
        </label>
      ) : null}

      <input
        id={fieldId}
        name={htmlName}
        type={type}
        className="canon-textfield-input"
        style={inputStyles}
        placeholder={placeholder}
        required={required}
        disabled={disabled}
        readOnly={readOnly}
        autoComplete={autoComplete}
        pattern={pattern}
        minLength={minLength}
        maxLength={maxLength}
        value={value}
        aria-invalid={error ? true : undefined}
        aria-describedby={describedBy}
        aria-required={required ? true : undefined}
      />

      {error ? (
        <p id={errorId} role="alert" style={helperStyles}>
          {error}
        </p>
      ) : description ? (
        <p id={descriptionId} style={helperStyles}>
          {description}
        </p>
      ) : null}
    </div>
  );
};

export default TextField;
