// packages/components/src/lib/interactive/GlassCard.svelte
<script lang="ts">
	/**
	 * GlassCard - Frosted glass card with hover shine effect
	 *
	 * Port of Maverick X pattern. Uses backdrop-filter for
	 * glass effect with gradient shine on hover.
	 *
	 * @example
	 * <GlassCard>
	 *   <h3>Feature Title</h3>
	 *   <p>Description text</p>
	 * </GlassCard>
	 */
	import { browser } from '$app/environment';

	interface Props {
		/** Card variant */
		variant?: 'default' | 'subtle' | 'elevated';
		/** Show shine effect on hover */
		showShine?: boolean;
		/** Padding size */
		padding?: 'none' | 'sm' | 'md' | 'lg';
		/** Border radius */
		radius?: 'sm' | 'md' | 'lg' | 'xl';
		/** Additional classes */
		class?: string;
		/** Children */
		children?: import('svelte').Snippet;
	}

	let {
		variant = 'default',
		showShine = true,
		padding = 'md',
		radius = 'lg',
		class: className = '',
		children
	}: Props = $props();

	// Check for reduced motion preference
	const prefersReducedMotion = browser
		? window.matchMedia('(prefers-reduced-motion: reduce)').matches
		: false;
</script>

<div
	class="glass-card {variant} padding-{padding} radius-{radius} {className}"
	class:show-shine={showShine && !prefersReducedMotion}
>
	<!-- Edge glow -->
	<div class="edge-glow"></div>

	<!-- Shine effect on hover -->
	{#if showShine && !prefersReducedMotion}
		<div class="shine"></div>
	{/if}

	<!-- Content -->
	<div class="content">
		{@render children?.()}
	</div>
</div>

<style>
	.glass-card {
		position: relative;
		overflow: hidden;
		background: var(--color-bg-surface, rgba(255, 255, 255, 0.05));
		border: 1px solid var(--color-border-default, rgba(255, 255, 255, 0.1));
		backdrop-filter: blur(12px) saturate(150%);
		-webkit-backdrop-filter: blur(12px) saturate(150%);
		transition:
			background var(--duration-micro, 200ms) var(--ease-standard),
			border-color var(--duration-micro, 200ms) var(--ease-standard),
			box-shadow var(--duration-micro, 200ms) var(--ease-standard),
			transform var(--duration-micro, 200ms) var(--ease-standard);
	}

	/* Variants */
	.glass-card.default {
		background: var(--color-bg-surface, rgba(255, 255, 255, 0.05));
	}

	.glass-card.subtle {
		background: var(--color-bg-subtle, rgba(255, 255, 255, 0.02));
		border-color: var(--color-border-default, rgba(255, 255, 255, 0.05));
	}

	.glass-card.elevated {
		background: var(--color-bg-elevated, rgba(255, 255, 255, 0.08));
		box-shadow: var(--shadow-lg, 0 10px 40px rgba(0, 0, 0, 0.3));
	}

	/* Hover states */
	.glass-card:hover {
		border-color: var(--color-border-emphasis, rgba(255, 255, 255, 0.2));
		box-shadow: var(--shadow-lg, 0 10px 40px rgba(0, 0, 0, 0.3));
	}

	.glass-card.elevated:hover {
		transform: translateY(-4px);
		box-shadow: var(--shadow-xl, 0 20px 60px rgba(0, 0, 0, 0.4));
	}

	/* Padding */
	.glass-card.padding-none {
		padding: 0;
	}
	.glass-card.padding-sm {
		padding: var(--space-sm, 1rem);
	}
	.glass-card.padding-md {
		padding: var(--space-md, 1.618rem);
	}
	.glass-card.padding-lg {
		padding: var(--space-lg, 2.618rem);
	}

	/* Border radius */
	.glass-card.radius-sm {
		border-radius: var(--radius-sm, 6px);
	}
	.glass-card.radius-md {
		border-radius: var(--radius-md, 8px);
	}
	.glass-card.radius-lg {
		border-radius: var(--radius-lg, 12px);
	}
	.glass-card.radius-xl {
		border-radius: var(--radius-xl, 16px);
	}

	/* Edge glow - subtle gradient at top */
	.edge-glow {
		position: absolute;
		inset: 0;
		background: linear-gradient(
			to bottom right,
			rgba(255, 255, 255, 0.1) 0%,
			transparent 50%,
			transparent 100%
		);
		pointer-events: none;
		opacity: 0.5;
	}

	/* Shine effect on hover */
	.shine {
		position: absolute;
		inset: 0;
		background: linear-gradient(
			to bottom right,
			rgba(255, 255, 255, 0.15) 0%,
			transparent 40%,
			transparent 100%
		);
		opacity: 0;
		transition: opacity var(--duration-standard, 300ms) var(--ease-standard);
		pointer-events: none;
	}

	.glass-card:hover .shine {
		opacity: 1;
	}

	/* Content */
	.content {
		position: relative;
		z-index: 1;
	}

	/* Reduced motion */
	@media (prefers-reduced-motion: reduce) {
		.glass-card {
			transition: none;
		}

		.glass-card.elevated:hover {
			transform: none;
		}

		.shine {
			display: none;
		}
	}
</style>

// packages/webflow-components/src/components/cards/GlassCard.tsx
import React, { CSSProperties, ReactNode } from 'react';
import { tokens, BrandVariant, getBrandColors } from '../../styles/tokens';

export type GlassVariant = 'light' | 'dark' | 'colored';

export interface GlassCardProps {
  /** Card content */
  children?: ReactNode;
  /** Visual variant of the glass effect */
  glassVariant?: GlassVariant;
  /** Brand color (for 'colored' variant) */
  brandVariant?: BrandVariant;
  /** Enable hover shine effect */
  showShine?: boolean;
  /** Padding size */
  padding?: 'sm' | 'md' | 'lg';
  /** Additional class name */
  className?: string;
}

export const GlassCard: React.FC<GlassCardProps> = ({
  children,
  glassVariant = 'light',
  brandVariant = 'default',
  showShine = true,
  padding = 'md',
  className = '',
}) => {
  const brand = getBrandColors(brandVariant);

  const getBackgroundColor = (): string => {
    switch (glassVariant) {
      case 'light':
        return 'rgba(255, 255, 255, 0.1)';
      case 'dark':
        return 'rgba(0, 0, 0, 0.1)';
      case 'colored':
        return `${brand.primary}1a`; // 10% opacity
    }
  };

  const getBorderColor = (): string => {
    switch (glassVariant) {
      case 'light':
        return 'rgba(255, 255, 255, 0.2)';
      case 'dark':
        return 'rgba(255, 255, 255, 0.1)';
      case 'colored':
        return `${brand.primary}33`; // 20% opacity
    }
  };

  const paddingSizes = {
    sm: tokens.spacing.sm,
    md: tokens.spacing.md,
    lg: tokens.spacing.lg,
  };

  const containerStyles: CSSProperties = {
    position: 'relative',
    overflow: 'hidden',
    padding: paddingSizes[padding],
    backgroundColor: getBackgroundColor(),
    border: `1px solid ${getBorderColor()}`,
    borderRadius: 0, // Maverick X: no border radius
    backdropFilter: 'blur(20px) saturate(150%)',
    WebkitBackdropFilter: 'blur(20px) saturate(150%)',
    boxShadow: tokens.shadows.xl,
    transition: `all ${tokens.animation.duration.standard} ${tokens.animation.easing.standard}`,
  };

  const shineStyles: CSSProperties = {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: 'linear-gradient(135deg, rgba(255,255,255,0.2) 0%, transparent 50%, transparent 100%)',
    opacity: 0,
    pointerEvents: 'none',
    transition: `opacity ${tokens.animation.duration.complex} ${tokens.animation.easing.standard}`,
  };

  const edgeGlowStyles: CSSProperties = {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: 'linear-gradient(135deg, rgba(255,255,255,0.1) 0%, transparent 100%)',
    opacity: 0.5,
    pointerEvents: 'none',
  };

  const contentStyles: CSSProperties = {
    position: 'relative',
    zIndex: 10,
  };

  // Hover styles via CSS
  const hoverCSS = `
    .mavx-glass-card:hover {
      box-shadow: ${tokens.shadows['2xl']};
    }
    .mavx-glass-card:hover .mavx-glass-shine {
      opacity: 1;
    }
  `;

  return (
    <div className={`mavx-glass-card ${className}`} style={containerStyles}>
      <style>{hoverCSS}</style>

      {/* Shine effect */}
      {showShine && <div className="mavx-glass-shine" style={shineStyles} />}

      {/* Edge glow */}
      <div style={edgeGlowStyles} />

      {/* Content */}
      <div style={contentStyles}>{children}</div>
    </div>
  );
};

export default GlassCard;
