// packages/canon/src/lib/components/Card.svelte
<script lang="ts">
	/**
	 * Card Component
	 *
	 * Standardized card with variants following CREATE SOMETHING standards.
	 * Uses canonical CSS custom properties for all design tokens.
	 */

	type CardVariant = 'standard' | 'elevated' | 'outlined' | 'glass';
	type CardRadius = 'sm' | 'md' | 'lg' | 'xl';
	type CardPadding = 'none' | 'sm' | 'md' | 'lg' | 'xl';

	interface Props {
		variant?: CardVariant;
		radius?: CardRadius;
		padding?: CardPadding;
		hover?: boolean;
		href?: string;
		class?: string;
		children?: import('svelte').Snippet;
		onclick?: (event: MouseEvent) => void;
	}

	let {
		variant = 'standard',
		radius = 'lg',
		padding = 'lg',
		hover = false,
		href,
		class: className = '',
		children,
		onclick
	}: Props = $props();

	// Padding map using layout utilities (acceptable per CSS Architecture standard)
	const paddingMap = {
		none: '',
		sm: 'p-4',
		md: 'p-6',
		lg: 'p-8',
		xl: 'p-12'
	};

	const baseClasses = `card card-${variant} card-radius-${radius} ${hover ? 'card-hover' : ''} ${paddingMap[padding]} ${className}`;
</script>

{#if href}
	<a {href} class={baseClasses} {onclick}>
		{#if children}
			{@render children()}
		{/if}
	</a>
{:else if onclick}
	<button type="button" class={baseClasses} {onclick}>
		{#if children}
			{@render children()}
		{/if}
	</button>
{:else}
	<div class={baseClasses}>
		{#if children}
			{@render children()}
		{/if}
	</div>
{/if}

<style>
	/* Base Card */
	.card {
		transition: all var(--duration-standard) var(--ease-standard);
	}

	/* Variants */
	.card-standard {
		background: var(--color-bg-elevated);
		border: 1px solid var(--color-border-default);
	}

	.card-elevated {
		background: var(--color-bg-elevated);
		border: 1px solid var(--color-border-default);
		box-shadow: var(--shadow-xl);
	}

	.card-outlined {
		background: transparent;
		border: 2px solid var(--color-border-emphasis);
	}

	/* Glass variant - "The Automation Layer" */
	.card-glass {
		background-color: var(--glass-bg-light);
		border: 1px solid var(--glass-border-light);
		backdrop-filter: blur(var(--glass-blur-md)) var(--glass-saturate-md);
	}

	.card-glass.card-hover:hover {
		background-color: var(--glass-bg-medium);
		border-color: var(--glass-border-medium);
		box-shadow: var(--glass-shadow-md);
	}

	/* Radius variants */
	.card-radius-sm {
		border-radius: var(--radius-sm);
	}

	.card-radius-md {
		border-radius: var(--radius-md);
	}

	.card-radius-lg {
		border-radius: var(--radius-lg);
	}

	.card-radius-xl {
		border-radius: var(--radius-xl);
	}

	/* Hover effect - Scale + Border Progression (Pattern 1) */
	.card-hover {
		cursor: pointer;
	}

	.card-hover:hover {
		transform: scale(var(--scale-micro));
		border-color: var(--color-border-emphasis);
		box-shadow: var(--shadow-lg);
	}

	.card-hover:active {
		transform: scale(var(--scale-subtle));
	}

	/* Focus states for accessibility */
	a.card:focus-visible,
	button.card:focus-visible,
	div.card:focus-visible {
		outline: 2px solid var(--color-focus);
		outline-offset: 2px;
	}

	/* Reset button styles when used as card */
	button {
		border: none;
		background: none;
		font: inherit;
		text-align: inherit;
		cursor: pointer;
		width: 100%;
	}
</style>

// .codex-tmp/removed-symphony-workspaces-20260315-115034/code-quality/lm-4e95ac36/packages/webflow-components/src/components/surfaces/Card.tsx
import React, { CSSProperties, ReactNode } from 'react';
import { tokens } from '../../styles/tokens';
import { Box, Stack, Text } from '../primitives';

export type CardVariant = 'standard' | 'elevated' | 'outlined' | 'glass';
export type CardRadius = 'sm' | 'md' | 'lg' | 'xl';
export type CardPadding = 'none' | 'sm' | 'md' | 'lg' | 'xl';

export interface CardProps {
  variant?: CardVariant;
  radius?: CardRadius;
  padding?: CardPadding;
  hover?: boolean;
  href?: string;
  title?: string;
  body?: string;
  className?: string;
  children?: ReactNode;
}

const paddingMap: Record<CardPadding, string> = {
  none: '0',
  sm: '1rem',
  md: '1.5rem',
  lg: '2rem',
  xl: '3rem',
};

const radiusMap: Record<CardRadius, string> = {
  sm: tokens.radii.sm,
  md: tokens.radii.md,
  lg: tokens.radii.lg,
  xl: tokens.radii.xl,
};

function getVariantStyles(variant: CardVariant): CSSProperties {
  switch (variant) {
    case 'elevated':
      return {
        background: tokens.colors.bgSurface,
        border: `1px solid ${tokens.colors.borderDefault}`,
        boxShadow: tokens.shadows.xl,
      };
    case 'outlined':
      return {
        background: 'transparent',
        border: `2px solid ${tokens.colors.borderEmphasis}`,
      };
    case 'glass':
      return {
        background: tokens.colors.overlay,
        border: `1px solid ${tokens.colors.borderEmphasis}`,
        backdropFilter: 'blur(20px) saturate(150%)',
        WebkitBackdropFilter: 'blur(20px) saturate(150%)',
      };
    case 'standard':
    default:
      return {
        background: tokens.colors.bgSurface,
        border: `1px solid ${tokens.colors.borderDefault}`,
      };
  }
}

export const Card: React.FC<CardProps> = ({
  variant = 'standard',
  radius = 'lg',
  padding = 'lg',
  hover = false,
  href,
  title,
  body,
  className = '',
  children,
}) => {
  const baseStyles: CSSProperties = {
    display: 'block',
    color: tokens.colors.fgPrimary,
    textDecoration: 'none',
    borderRadius: radiusMap[radius],
    padding: paddingMap[padding],
    transition: `all ${tokens.animation.duration.standard} ${tokens.animation.easing.standard}`,
    ...getVariantStyles(variant),
  };

  const interactiveStyles = hover
    ? `
      .canon-card-hover:hover {
        transform: scale(1.01);
        border-color: ${tokens.colors.borderEmphasis};
        box-shadow: ${tokens.shadows.lg};
      }
      .canon-card-hover:active {
        transform: scale(0.995);
      }
      .canon-card-hover:focus-visible {
        outline: 2px solid ${tokens.colors.focus};
        outline-offset: 2px;
      }
    `
    : `
      .canon-card-static:focus-visible {
        outline: 2px solid ${tokens.colors.focus};
        outline-offset: 2px;
      }
    `;

  const cardClassName = `${hover ? 'canon-card-hover' : 'canon-card-static'} ${className}`.trim();

  const content = children ?? (
    <Stack gap="sm">
      {title ? (
        <Text as="h3" size="h4" weight="bold" style={{ lineHeight: tokens.typography.lineHeight.tight }}>
          {title}
        </Text>
      ) : null}
      {body ? (
        <Text as="p" tone="secondary" size="body">
          {body}
        </Text>
      ) : null}
    </Stack>
  );

  const cardChildren = (
    <>
      <style>{interactiveStyles}</style>
      {content}
    </>
  );

  if (href) {
    return (
      <Box as="a" className={cardClassName} style={baseStyles}>
        {cardChildren}
      </Box>
    );
  }

  return (
    <Box as="div" className={cardClassName} style={baseStyles}>
      {cardChildren}
    </Box>
  );
};

export default Card;
